version: '3'
services:
  hacksaw-blog:
    container_name: hacksaw-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: sh -c "yarn dev"
    ports:
      - '3000:3000'
